add create table and request scripts
IvanIlin22/SQL pull request #1
Opened 2020-12-08 21:45 UTC by IvanIlin22

created tables and ran a query

2020-12-09 12:43 UTC, eldmitrieva requested changes

2020-12-09 12:43 UTC, eldmitrieva commented on hh_response.sql
> +limit (5);
limit (5) -> LIMIT 5

2020-12-09 12:43 UTC, eldmitrieva commented on hh_response.sql
> +	e.employer_name
если у тебя несколько работодателей имеют одинаковое название, их отклики отклики посчитаются вместе. так что тут либо делать employer_name уникальным, либо использовать тут employer_id (это будет правильнее, все-таки компании с одинаковыми названиями встречаются)

2020-12-09 12:43 UTC, eldmitrieva commented on hh_response.sql
> +	percentile_cont(0.98) WITHIN GROUP(ORDER BY count)
медиана это percentile_cont(0.5)

2020-12-09 12:43 UTC, eldmitrieva commented on hh_response.sql
> +	age(r.date_response, v.date_creation)
тут лучше указать алиас

2020-12-09 12:43 UTC, eldmitrieva commented on hh_response.sql
> +INNER JOIN employer e ON v.employer_id = e.employer_id
работодатели, у которых нет вакансий, не учитываются, а должны

2020-12-09 12:43 UTC, eldmitrieva commented on hh_response.sql
> +GROUP BY e.employer_name;
группировать лучше по employer_id, иначе ты работодателей с одинаковым названием схлопываешь в одного

2020-12-09 21:35 UTC, IvanIlin22 commented on hh_response.sql
> +limit (5);
Испарвил

2020-12-09 21:36 UTC, IvanIlin22 commented on hh_response.sql
> +	e.employer_name
исправил

2020-12-09 21:36 UTC, IvanIlin22 commented on hh_response.sql
> +INNER JOIN employer e ON v.employer_id = e.employer_id
исправил на right join

2020-12-09 21:37 UTC, IvanIlin22 commented on hh_response.sql
> +	age(r.date_response, v.date_creation)
добавил алиас

2020-12-09 21:37 UTC, IvanIlin22 commented on hh_response.sql
> +	percentile_cont(0.98) WITHIN GROUP(ORDER BY count)
исправил на 0.5

2020-12-09 21:38 UTC, IvanIlin22 commented on hh_response.sql
> +GROUP BY e.employer_name;
сгруппировал по employer_id

2020-12-20 19:15 UTC, eldmitrieva requested changes

2020-12-20 19:15 UTC, eldmitrieva commented on hh_response.sql
> +	max(time) AS max_time,
тут получается не время до первого отклика, а время до последнего отклика

2020-12-21 20:18 UTC, IvanIlin22 commented on hh_response.sql
> +	max(time) AS max_time,
Исправил

2020-12-22 10:34 UTC, eldmitrieva requested changes

2020-12-22 10:34 UTC, eldmitrieva commented on hh_response.sql
> +FROM min_response
ты в min_response группируешь данные по вакансиям и городам, здесь никакой дополнительной группировки нет, так что итоговая группировка будет не по городам

2020-12-22 10:34 UTC, eldmitrieva commented on hh_response.sql
> +WHERE min_time IN (
возможно, на твоих тестовых данных это сработает, но в общем случае нет. например, если min_time для Саратова не является минимальным в Саратове, но равно минимальному min_time в Москве

2020-12-23 09:12 UTC, eldmitrieva requested changes

2020-12-23 09:12 UTC, eldmitrieva commented on hh_response.sql
> +GROUP BY employer_name
тут осталась группировка по наванию компании

2020-12-23 09:12 UTC, eldmitrieva commented on hh_response.sql
> +FROM response r
если у компании нет откликов, то она не попадет в топ, надо поправить, чтобы могла попасть

2020-12-24 14:42 UTC, eldmitrieva approved these changes

2020-12-28 20:43 UTC, merged